# Permalinks
permalink:      pretty

# Setup
title:          The Diary of an Entreprenur 
description:    Life notes 
baseurl:        
url:            "https://techkunstler.in"

color:          primary 

author:
  name:         Santhosh K S 
  url:          https://techkunstler.in
  email:        santhosh@techkunstler.com                                   # Place your email here
  github:       Santhosh-KS                        # Place your GitHub username here
  linkedIn:     santhosh-k-s-07542623              # Place your LinkdIn username here
  # twitter:      Linuxneitor                        # Place your twitter username here
  # mastodon:     https://mastodon.social/@jsalvador # Place your profile URL here
# twitter:
  # username: Linuxneitor
  # card: summary
# locale: es_ES

# Assets
sass:
  style:        compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        4.3.3
paginate:       5                                  # Default pagination is 5 post per page
paginate_path: "/page:num/"

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
